### ISSUE TITLE
Add Python 3.13 support in CI

### ISSUE THREAD

**Issue by PaTara43** [polkascan/py-bip39-bindings#21]
It seems like the runners [don't](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#python) automatically use Python 3.13, but htere is a way to add support manually (e.g. [this ](https://github.com/jupyter-server/pycrdt/actions/runs/11251137381/workflow#L95)and [this](https://github.com/pydantic/pydantic-core/blob/main/.github/workflows/ci.yml#L427)). Are there any limitations on adding that? If not, is it possible to do so? Same goes for https://github.com/polkascan/py-ed25519-bindings and https://github.com/polkascan/py-sr25519-bindings
Thanks!

p.s. perhaps, the `find-interpreter` arg may be kept, but python version added on the previous step ([source](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input))
```
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '>=3.9 <3.14'
- run: python my_script.py
```
